# Generated by Django 3.0.2 on 2020-01-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsc_connect_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsc',
            name='status',
            field=models.CharField(choices=[('0', 'draft'), ('1', 'published')], max_length=1),
        ),
    ]
